version: "3.9"
services:
  ydb:
    image: cr.yandex/yc/yandex-docker-local-ydb:latest
    hostname: localhost # for good discovery
    environment:
      YDB_ANONYMOUS_CREDENTIALS: 1
    ports:
      - "2135:2135"
      - "2136:2136" # port without tls
