[package]
publish=true
name = "ydb"
version = "0.4.2"
authors = ["rekby <timofey.koolin@gmail.com>"]
edition = "2021"
license = "Apache-2.0"
description = "Crate contains generated low-level grpc code from YDB API protobuf, used as base for ydb crate"
repository = "https://github.com/ydb-platform/ydb-rs-sdk/tree/master/ydb"

[dependencies]
async-trait="0.1"
derivative="2"
http = "0.2"
itertools="0.10"
num = "0.4"
mockall = "0.10"
once_cell = "1.8"
prost = "0.11.0"
prost-types = "0.11.1"
pbjson-types = "0.4.0"
rand = "0.8"
reqwest = {version="0.11", features = ["blocking", "json","rustls"], default-features = false}
serde={version="1.0", features=["derive"]}
serde_json="1.0"
strum = { version = "0.21", features = ["derive"] }
tokio = { version = "1.17", features = ["full"]}
tracing = "0.1"
tracing-test = "0.2.1"
tracing-subscriber = "0.3"
tonic = {version= "0.8.1", features=["tls"]}
tower = "0.4"
url="2.2"
ydb-grpc = { version = "0.0.8", path="../ydb-grpc"}

[dev-dependencies]
async_once="0.2"
lazy_static="1.4"
ntest="0.7"
