[package]
name = "ydb-todo-list"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ydb = "0.6.2"
tokio = { version = "1", features = ["full"] }
